### ISSUE TITLE
Two .so files are needed to be copied by shell script

### ISSUE THREAD

**Issue by zzrcxb** [yaokai1117/DemoCTP#4]
You need to copy thostmduserapi.so and thosttraderapi.so (they are located in DemoCTP/dependency/vnctp/ctpapi/) to root folder. Otherwise, you will receive an ImportError

**Comment by yaokai1117** [comment]
I add this command to install.sh
export LD_LIBRARY_PATH=$(pwd)/dependency/vnctp/ctpapi:$LD_LIBRARY_PATH
I think this will solve the problem you mentioned (works well on my machine).
