### ISSUE TITLE
Remove deprecated function or class

### ISSUE THREAD

**Issue by zzrcxb** [yaokai1117/DemoCTP#5]
In the latest version of matplotlib (2.0.0), NavigationToolbar2QTAgg has been removed. So please update import statement in `DemoCTP/chartPlotter.py` from
`from matplotlib.backends.backend_qt4agg import NavigationToolbar2QTAgg as NavigationToolbar`
to
`from matplotlib.backends.backend_qt4agg import NavigationToolbar2QT as NavigationToolbar`
For more information about API changes, please follow the link below:
http://matplotlib.org/api/api_changes.html#remove-navigationtoolbar2qtagg

**Comment by yaokai1117** [comment]
Fixed! Thanks.
